#!/bin/bash
# pgcli Patroni entrypoint: starts sshd for backup support, then launches
# Patroni as PID 1. Patroni owns the postmaster lifecycle; its config is
# bind-mounted read-only at /patroni/patroni.yml by pgcli.
#
# The container runs as postgres (uid 999) via USER directive. With
# --userns=keep-id, uid 999 maps to the host user's UID, giving access
# to bind-mounted data dirs owned by the host user. SSH host keys are
# generated at runtime in /tmp (writable by postgres) rather than at
# image build time in /etc/ssh (root-only).
set -e

# --- sshd setup in /tmp (writable by postgres uid) ---
SSHD_DIR="/tmp/pgcli-sshd"
mkdir -p "$SSHD_DIR"

# Generate host keys if absent. Each container gets unique keys.
for alg in rsa ed25519 ecdsa; do
    keyfile="$SSHD_DIR/ssh_host_${alg}_key"
    if [ ! -f "$keyfile" ]; then
        ssh-keygen -t "$alg" -f "$keyfile" -N '' -q
    fi
done

# Authorized keys directory.
AUTH_KEYS_DIR="$SSHD_DIR/authorized_keys"
mkdir -p "$AUTH_KEYS_DIR"

# Install the backup SSH public keys for sshd. Two sources are merged:
#   /run/pgcli/backup_id_rsa.pub       — this host's backup-container key
#   /run/pgcli/authorized_keys_cluster — every cluster member's backup key,
#                                        merged by `pg backup setup` so any
#                                        host's backup container can SSH into
#                                        this member (cluster-wide stanzas make
#                                        pgBackRest probe all pg*-host entries).
# Overwrite (not append): the file lives under /tmp and must not accumulate
# keys across restarts. A key present in both sources is harmless (sshd reads
# line by line). Each source gets its own newline: key files generated by older
# pgcli builds lack a trailing newline, and without the separator the second
# file's key would merge onto the first line, which sshd then rejects. An extra
# blank line between sources is ignored by sshd.
{
    [ -f /run/pgcli/backup_id_rsa.pub ] && { cat /run/pgcli/backup_id_rsa.pub; echo; }
    [ -f /run/pgcli/authorized_keys_cluster ] && { cat /run/pgcli/authorized_keys_cluster; echo; }
} > "$AUTH_KEYS_DIR/postgres"
chmod 600 "$AUTH_KEYS_DIR/postgres"

# AuthorizedKeysFile lists two sources, tried by sshd in order per login:
# the local copy assembled above, and the cluster-wide file straight from its
# bind mount. Reading the mount directly (not only the boot-time copy) is what
# makes `pg backup setup` key merges live inside running containers — sshd
# opens the file on every auth attempt.
cat > "$SSHD_DIR/sshd_config" <<SSHD_EOF
ListenAddress 0.0.0.0
Port ${PGCLI_SSH_PORT:-22}
HostKey $SSHD_DIR/ssh_host_rsa_key
HostKey $SSHD_DIR/ssh_host_ed25519_key
HostKey $SSHD_DIR/ssh_host_ecdsa_key
PidFile $SSHD_DIR/sshd.pid
AuthorizedKeysFile $AUTH_KEYS_DIR/%u /run/pgcli/authorized_keys_cluster
StrictModes no
PasswordAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
UsePAM no
Subsystem sftp /usr/lib/openssh/sftp-server
SSHD_EOF

# Start sshd. If it fails, log and continue — Patroni is the primary workload.
/usr/sbin/sshd -f "$SSHD_DIR/sshd_config" 2>"$SSHD_DIR/sshd.log" || {
    echo "WARNING: sshd failed to start (see $SSHD_DIR/sshd.log)"
    cat "$SSHD_DIR/sshd.log" >&2
}

# Hand off to Patroni as PID 1.
exec patroni /patroni/patroni.yml
