version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: pg
    binary: pg
    main: .
    ldflags:
      - -s -w
      - -X github.com/mars-base/pgcli/internal/cli.version={{.Version}}
      - -X github.com/mars-base/pgcli/internal/cli.commit={{.Commit}}
      - -X github.com/mars-base/pgcli/internal/cli.buildDate={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: mars-base
    name: pgcli
  draft: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
