package config

import (
	"path/filepath"
	"testing"
)

func TestRedisDefaults(t *testing.T) {
	cfg := Default()
	cfg.Addons.Redis = map[string]RedisConfig{
		"cache": {},
	}

	cfg.ApplyDefaults()

	rc, ok := cfg.Addons.Redis["cache"]
	if !ok {
		t.Fatal("redis addon missing after ApplyDefaults")
	}
	if rc.Name != "cache" {
		t.Errorf("name = %q, want cache", rc.Name)
	}
	if rc.ContainerName != "pgcli-redis-cache" {
		t.Errorf("container name = %q, want pgcli-redis-cache", rc.ContainerName)
	}
	if rc.Version != DefaultRedisMajor {
		t.Errorf("version = %q, want %q", rc.Version, DefaultRedisMajor)
	}
	wantTag, _ := RedisImageTagForMajor(DefaultRedisMajor)
	if rc.ImageTag != wantTag {
		t.Errorf("image tag = %q, want %q", rc.ImageTag, wantTag)
	}
	if rc.Listen != "0.0.0.0" {
		t.Errorf("listen = %q, want 0.0.0.0 (requirepass is the gate, so the default publishes the port)", rc.Listen)
	}
	// Password is generated by the CLI install handler, never by ApplyDefaults
	// (which must stay deterministic — it runs on every load).
	if rc.Password != "" {
		t.Errorf("password = %q, want empty (CLI-generated)", rc.Password)
	}
	// DataDir is resolved by the manager at container-creation time, not here.
	if rc.DataDir != "" {
		t.Errorf("data dir = %q, want empty (manager-resolved)", rc.DataDir)
	}
	// Port auto-assignment is exercised with a high base in
	// TestRedisPortAssignment; the 6379 default only guarantees it lands
	// somewhere at or above the base.
	if rc.Port < cfg.RedisStartPort {
		t.Errorf("port %d below base %d", rc.Port, cfg.RedisStartPort)
	}
}

// Version "7" resolves through the same table lookup; an explicit ImageTag is
// never rewritten, and an unknown Version with an explicit ImageTag is left
// alone (it came from --image, whose precedence the CLI enforces).
func TestRedisVersionResolution(t *testing.T) {
	tag7, ok := RedisImageTagForMajor("7")
	if !ok {
		t.Fatal("major 7 missing from redisMajorImages")
	}

	cfg := Default()
	cfg.Addons.Redis = map[string]RedisConfig{
		"legacy":  {Version: "7"},
		"custom":  {Version: "7", ImageTag: "registry.local/redis:7.2.4"},
		"weird":   {Version: "9", ImageTag: "docker.io/library/redis:9.0.0"},
		"noimage": {Version: "9"},
	}

	cfg.ApplyDefaults()

	if got := cfg.Addons.Redis["legacy"]; got.ImageTag != tag7 || got.Version != "7" {
		t.Errorf("legacy = version %q tag %q, want 7 / %q", got.Version, got.ImageTag, tag7)
	}
	if got := cfg.Addons.Redis["custom"]; got.ImageTag != "registry.local/redis:7.2.4" {
		t.Errorf("explicit image tag rewritten: %q", got.ImageTag)
	}
	if got := cfg.Addons.Redis["weird"]; got.ImageTag != "docker.io/library/redis:9.0.0" || got.Version != "9" {
		t.Errorf("unknown version with explicit tag mutated: version=%q tag=%q", got.Version, got.ImageTag)
	}
	// Unknown version without a tag: nothing to look up, tag stays empty so the
	// install surfaces as an image-not-found pull error, not a silent rewrite.
	if got := cfg.Addons.Redis["noimage"]; got.ImageTag != "" {
		t.Errorf("unknown version without tag backfilled to %q, want empty", got.ImageTag)
	}
}

func TestRedisSaveLoadRoundTrip(t *testing.T) {
	path := filepath.Join(t.TempDir(), "pg.yaml")

	cfg := Default()
	cfg.Addons.Redis = map[string]RedisConfig{
		"cache": {
			ContainerName: "pgcli-redis-cache",
			Name:          "cache",
			Version:       "7",
			ImageTag:      redisMajorImages["7"],
			DataDir:       "/srv/redis/cache",
			Listen:        "127.0.0.1",
			Port:          36399,
			Password:      "aX9kQ2mZx7Lp4RtVbNcE",
			MaxMemory:     "256mb",
			// The persistence/eviction knobs must survive a save/load too —
			// they ride the Addons passthrough in displayConfig, and a typo
			// in a yaml tag would silently reset them.
			AOF:             true,
			AppendFsync:     "always",
			MaxMemoryPolicy: "noeviction",
			SaveSchedule:    "900 1 300 10",
			Autostart:       true,
		},
		// The replica role is stored, not re-derived: `pg addon start` rebuilds
		// --replicaof from these two fields with no master lookup.
		"cache-r": {
			ContainerName: "pgcli-redis-cache-r",
			Name:          "cache-r",
			Version:       "7",
			ImageTag:      redisMajorImages["7"],
			Port:          36400,
			Password:      "aX9kQ2mZx7Lp4RtVbNcE",
			ReplicaHost:   "127.0.0.1",
			ReplicaPort:   36399,
		},
	}
	if err := cfg.Save(path); err != nil {
		t.Fatalf("save: %v", err)
	}

	got, err := Load(path)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	rc, ok := got.Addons.Redis["cache"]
	if !ok {
		t.Fatal("redis addon not persisted")
	}
	if rc.Version != "7" || rc.ImageTag != redisMajorImages["7"] {
		t.Errorf("version/image not persisted: %q / %q", rc.Version, rc.ImageTag)
	}
	if rc.Port != 36399 {
		t.Errorf("port not persisted: %d", rc.Port)
	}
	if rc.Password != "aX9kQ2mZx7Lp4RtVbNcE" {
		t.Errorf("password not persisted: %q", rc.Password)
	}
	if rc.MaxMemory != "256mb" {
		t.Errorf("maxmemory not persisted: %q", rc.MaxMemory)
	}
	if !rc.AOF {
		t.Error("aof not persisted")
	}
	if rc.AppendFsync != "always" {
		t.Errorf("appendfsync not persisted: %q", rc.AppendFsync)
	}
	if rc.MaxMemoryPolicy != "noeviction" {
		t.Errorf("maxmemory_policy not persisted: %q", rc.MaxMemoryPolicy)
	}
	if rc.SaveSchedule != "900 1 300 10" {
		t.Errorf("save not persisted: %q", rc.SaveSchedule)
	}
	if rc.Listen != "127.0.0.1" {
		t.Errorf("listen not persisted: %q", rc.Listen)
	}
	if rc.DataDir != "/srv/redis/cache" {
		t.Errorf("data dir not persisted: %q", rc.DataDir)
	}
	if !rc.Autostart {
		t.Error("autostart not persisted")
	}

	rr, ok := got.Addons.Redis["cache-r"]
	if !ok {
		t.Fatal("replica addon not persisted")
	}
	if rr.ReplicaHost != "127.0.0.1" || rr.ReplicaPort != 36399 {
		t.Errorf("replica target not persisted: %q:%d", rr.ReplicaHost, rr.ReplicaPort)
	}
	if _, ok := got.Addons.Redis["cache"]; !ok {
		t.Fatal("master addon lost when a replica shares the map")
	}

	// A second ApplyDefaults must not move the assigned port, rewrite the
	// version, or touch the stored password.
	got.ApplyDefaults()
	again := got.Addons.Redis["cache"]
	if again.Port != 36399 || again.Version != "7" || again.Password != "aX9kQ2mZx7Lp4RtVbNcE" {
		t.Errorf("ApplyDefaults mutated stored values: port=%d version=%q", again.Port, again.Version)
	}
}

// Redis owns its port pool (redis_start_port), independent of the object
// stores' shared minio pool. A high unused base keeps the live-listener scan
// from perturbing exact expectations (same convention as
// TestMinioSiloRustfsSharedPortPool).
func TestRedisPortAssignment(t *testing.T) {
	cfg := Default()
	cfg.RedisStartPort = 36379
	cfg.Addons.Redis = map[string]RedisConfig{
		"b": {},
		"a": {Port: 36876}, // explicit, above the base
		"c": {},
	}

	cfg.ApplyDefaults()

	// Names are drawn in sorted order (a, b, c); a's explicit port pushes the
	// cursor past it before b and c draw.
	if got := cfg.Addons.Redis["a"]; got.Port != 36876 {
		t.Errorf("explicit port changed: %d", got.Port)
	}
	if got := cfg.Addons.Redis["b"]; got.Port != 36877 {
		t.Errorf("b port = %d, want 36877 (cursor must skip reserved port)", got.Port)
	}
	if got := cfg.Addons.Redis["c"]; got.Port != 36878 {
		t.Errorf("c port = %d, want 36878", got.Port)
	}

	// The redis pool must not collide with the minio pool on the same host.
	cfg.Addons.Minio = map[string]MinioConfig{"store": {}}
	cfg.MinioStartPort = 9000
	cfg.ApplyDefaults()
	if m := cfg.Addons.Minio["store"]; m.APIPort == cfg.Addons.Redis["c"].Port || m.ConsolePort == cfg.Addons.Redis["c"].Port {
		t.Errorf("minio pair %d/%d collided with redis port %d", m.APIPort, m.ConsolePort, cfg.Addons.Redis["c"].Port)
	}
}

func TestRedisMajorForImageTag(t *testing.T) {
	cases := []struct {
		imageTag string
		want     string
	}{
		{"docker.io/library/redis:7.4.11", "7"},
		{"docker.io/library/redis:8.10.2", "8"},
		{"redis:7.2.4", "7"},
		{"docker.io/library/redis:9.0.0", ""},  // major not in the table
		{"docker.io/library/redis:latest", ""}, // not a digit run
		{"docker.io/library/redis", ""},        // no tag separator
		{"quay.io/valkey/valkey:8", "8"},
	}
	for _, tc := range cases {
		if got := RedisMajorForImageTag(tc.imageTag); got != tc.want {
			t.Errorf("RedisMajorForImageTag(%q) = %q, want %q", tc.imageTag, got, tc.want)
		}
	}
}

func TestRedisMajors(t *testing.T) {
	majors := RedisMajors()
	if len(majors) != len(redisMajorImages) {
		t.Fatalf("RedisMajors returned %d entries, table has %d", len(majors), len(redisMajorImages))
	}
	for i := 1; i < len(majors); i++ {
		if majors[i-1] >= majors[i] {
			t.Errorf("RedisMajors not sorted: %v", majors)
			break
		}
	}
	if _, ok := RedisImageTagForMajor("7"); !ok {
		t.Error("major 7 not resolvable")
	}
	if _, ok := RedisImageTagForMajor("8"); !ok {
		t.Error("major 8 not resolvable")
	}
	if _, ok := RedisImageTagForMajor("6"); ok {
		t.Error("major 6 unexpectedly resolvable")
	}
}
