package podman

// PigstyExt contains metadata for a non-builtin PostgreSQL extension
// from the Pigsty DEB repository (https://pigsty.cc/ext/list/).
// Source: pigsty.cc/ext/list/ (2026-08-31)
type PigstyExt struct {
	Package      string // apt package suffix (postgresql-18-<Package>)
	NeedsPreload bool   // must be in shared_preload_libraries
	Repo         string // source repo: PIGSTY, PGDG, MIXED
}

// PigstyExtMap contains 395 non-builtin extensions from the Pigsty catalog.
// Keyed by SQL extension name (as used in CREATE EXTENSION).
// The Package field is the apt package suffix: postgresql-18-<Package>.
var PigstyExtMap = map[string]PigstyExt{
	"acl": {Package: "acl", NeedsPreload: false, Repo: "PIGSTY"},
	"address_standardizer": {Package: "postgis-3", NeedsPreload: false, Repo: "PGDG"},
	"address_standardizer_data_us": {Package: "postgis-3", NeedsPreload: false, Repo: "PGDG"},
	"age": {Package: "age", NeedsPreload: true, Repo: "PIGSTY"},
	"aggs_for_arrays": {Package: "aggs-for-arrays", NeedsPreload: false, Repo: "PIGSTY"},
	"aggs_for_vecs": {Package: "aggs-for-vecs", NeedsPreload: false, Repo: "PIGSTY"},
	"argm": {Package: "argm", NeedsPreload: false, Repo: "PIGSTY"},
	"arraymath": {Package: "pg-arraymath", NeedsPreload: false, Repo: "PIGSTY"},
	"asn1oid": {Package: "asn1oid", NeedsPreload: false, Repo: "MIXED"},
	"base36": {Package: "base36", NeedsPreload: false, Repo: "PIGSTY"},
	"base62": {Package: "base62", NeedsPreload: false, Repo: "PIGSTY"},
	"bgw_replstatus": {Package: "bgw-replstatus", NeedsPreload: true, Repo: "PGDG"},
	"biscuit": {Package: "biscuit", NeedsPreload: false, Repo: "PIGSTY"},
	"byteamagic": {Package: "pg-byteamagic", NeedsPreload: false, Repo: "PIGSTY"},
	"bzip": {Package: "bzip", NeedsPreload: false, Repo: "PIGSTY"},
	"cat_tools": {Package: "cat-tools", NeedsPreload: false, Repo: "PIGSTY"},
	"chkpass": {Package: "chkpass", NeedsPreload: false, Repo: "PIGSTY"},
	"citus": {Package: "citus", NeedsPreload: true, Repo: "PIGSTY"},
	"citus_columnar": {Package: "citus", NeedsPreload: false, Repo: "PIGSTY"},
	"collection": {Package: "collection", NeedsPreload: false, Repo: "PIGSTY"},
	"columnar": {Package: "hydra", NeedsPreload: false, Repo: "PIGSTY"},
	"convert": {Package: "convert", NeedsPreload: false, Repo: "PIGSTY"},
	"count_distinct": {Package: "count-distinct", NeedsPreload: false, Repo: "MIXED"},
	"country": {Package: "pg-country", NeedsPreload: false, Repo: "PIGSTY"},
	"cron_utils": {Package: "cron-utils", NeedsPreload: false, Repo: "PIGSTY"},
	"cryptint": {Package: "cryptint", NeedsPreload: false, Repo: "PIGSTY"},
	"currency": {Package: "pg-currency", NeedsPreload: false, Repo: "PIGSTY"},
	"data_historization": {Package: "data-historization", NeedsPreload: false, Repo: "PIGSTY"},
	"datasketches": {Package: "datasketches", NeedsPreload: false, Repo: "PIGSTY"},
	"dbt2": {Package: "dbt2", NeedsPreload: false, Repo: "MIXED"},
	"ddl_historization": {Package: "ddl-historization", NeedsPreload: false, Repo: "PIGSTY"},
	"ddlx": {Package: "ddlx", NeedsPreload: false, Repo: "MIXED"},
	"ddsketch": {Package: "ddsketch", NeedsPreload: false, Repo: "PIGSTY"},
	"debversion": {Package: "debversion", NeedsPreload: false, Repo: "PGDG"},
	"duckdb_fdw": {Package: "duckdb-fdw", NeedsPreload: false, Repo: "PIGSTY"},
	"emailaddr": {Package: "pg-emailaddr", NeedsPreload: false, Repo: "PIGSTY"},
	"emaj": {Package: "emaj", NeedsPreload: false, Repo: "PIGSTY"},
	"envvar": {Package: "pg-envvar", NeedsPreload: false, Repo: "PIGSTY"},
	"external_file": {Package: "external-file", NeedsPreload: false, Repo: "PIGSTY"},
	"extra_window_functions": {Package: "extra-window-functions", NeedsPreload: false, Repo: "PGDG"},
	"faker": {Package: "faker", NeedsPreload: false, Repo: "MIXED"},
	"fbsql": {Package: "fbsql", NeedsPreload: false, Repo: "PIGSTY"},
	"financial": {Package: "pg-financial", NeedsPreload: false, Repo: "PIGSTY"},
	"fio": {Package: "pg-fio", NeedsPreload: false, Repo: "PIGSTY"},
	"first_last_agg": {Package: "first-last-agg", NeedsPreload: false, Repo: "MIXED"},
	"floatfile": {Package: "floatfile", NeedsPreload: false, Repo: "PIGSTY"},
	"floatvec": {Package: "floatvec", NeedsPreload: false, Repo: "PIGSTY"},
	"fsm_core": {Package: "fsm-core", NeedsPreload: false, Repo: "PIGSTY"},
	"geoip": {Package: "geoip", NeedsPreload: false, Repo: "MIXED"},
	"graph": {Package: "pggraph", NeedsPreload: false, Repo: "PIGSTY"},
	"gzip": {Package: "gzip", NeedsPreload: false, Repo: "MIXED"},
	"h3": {Package: "h3", NeedsPreload: false, Repo: "PGDG"},
	"h3_postgis": {Package: "h3", NeedsPreload: false, Repo: "PGDG"},
	"hashlib": {Package: "pg-hashlib", NeedsPreload: false, Repo: "PIGSTY"},
	"hashtypes": {Package: "hashtypes", NeedsPreload: false, Repo: "PIGSTY"},
	"hll": {Package: "hll", NeedsPreload: false, Repo: "PGDG"},
	"hstore_pllua": {Package: "pllua", NeedsPreload: false, Repo: "MIXED"},
	"hstore_plluau": {Package: "pllua", NeedsPreload: false, Repo: "MIXED"},
	"hstore_plruby": {Package: "plruby", NeedsPreload: false, Repo: "PIGSTY"},
	"http": {Package: "http", NeedsPreload: false, Repo: "PGDG"},
	"hunspell_cs_cz": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_de_de": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_en_us": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_fr": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_ne_np": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_nl_nl": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_nn_no": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_pt_pt": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_ru_ru": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_ru_ru_aot": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hypopg": {Package: "hypopg", NeedsPreload: false, Repo: "PGDG"},
	"icu_ext": {Package: "icu-ext", NeedsPreload: false, Repo: "PGDG"},
	"imgsmlr": {Package: "imgsmlr", NeedsPreload: false, Repo: "PIGSTY"},
	"index_advisor": {Package: "index-advisor", NeedsPreload: false, Repo: "PIGSTY"},
	"ip4r": {Package: "ip4r", NeedsPreload: false, Repo: "PGDG"},
	"jsonb_plruby": {Package: "plruby", NeedsPreload: false, Repo: "PIGSTY"},
	"jsonschema": {Package: "jsonschema", NeedsPreload: false, Repo: "PIGSTY"},
	"jsquery": {Package: "jsquery", NeedsPreload: false, Repo: "PGDG"},
	"l10n_table_dependent_extension": {Package: "pg-xenophile", NeedsPreload: false, Repo: "PIGSTY"},
	"lower_quantile": {Package: "lower-quantile", NeedsPreload: false, Repo: "PIGSTY"},
	"ltree_plruby": {Package: "plruby", NeedsPreload: false, Repo: "PIGSTY"},
	"md5hash": {Package: "md5hash", NeedsPreload: false, Repo: "PIGSTY"},
	"meta": {Package: "pg-meta", NeedsPreload: false, Repo: "PIGSTY"},
	"mobilitydb": {Package: "mobilitydb", NeedsPreload: true, Repo: "MIXED"},
	"mobilitydb_datagen": {Package: "mobilitydb", NeedsPreload: false, Repo: "MIXED"},
	"numeral": {Package: "numeral", NeedsPreload: false, Repo: "MIXED"},
	"ogr_fdw": {Package: "ogr-fdw", NeedsPreload: false, Repo: "PGDG"},
	"omni": {Package: "omnigres", NeedsPreload: true, Repo: "PIGSTY"},
	"omni_auth": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_aws": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_cloudevents": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_containers": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_credentials": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_csv": {Package: "omni_csv", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_datasets": {Package: "omni_datasets", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_email": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_http": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_httpc": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_httpd": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_id": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_json": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_kube": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_ledger": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_manifest": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_mimetypes": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_os": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_polyfill": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_python": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_regex": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_rest": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_schema": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_seq": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_service": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_session": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_shmem": {Package: "omni_shmem", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_sql": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_sqlite": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_test": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_txn": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_types": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_var": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_vfs": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_vfs_types_v1": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_web": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_worker": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_xml": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_yaml": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omnisketch": {Package: "omnisketch", NeedsPreload: false, Repo: "PIGSTY"},
	"onesparse": {Package: "one_sparse", NeedsPreload: false, Repo: "PIGSTY"},
	"online_advisor": {Package: "online-advisor", NeedsPreload: true, Repo: "PIGSTY"},
	"orioledb": {Package: "orioledb", NeedsPreload: true, Repo: "PIGSTY"},
	"parray_gin": {Package: "parray-gin", NeedsPreload: false, Repo: "PIGSTY"},
	"periods": {Package: "periods", NeedsPreload: false, Repo: "PIGSTY"},
	"permuteseq": {Package: "permuteseq", NeedsPreload: false, Repo: "PIGSTY"},
	"pg4ml": {Package: "pg4ml", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_accumulator": {Package: "pg-accumulator", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_ai_query": {Package: "ai-query", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_background": {Package: "pg-background", NeedsPreload: false, Repo: "PGDG"},
	"pg_base58": {Package: "pg-base58", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_bestmatch": {Package: "pg-bestmatch", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_bigm": {Package: "pg-bigm", NeedsPreload: true, Repo: "MIXED"},
	"pg_bikram_sambat": {Package: "pg-bikram-sambat", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_cardano": {Package: "pg-cardano", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_catcheck": {Package: "pg-catcheck", NeedsPreload: false, Repo: "PGDG"},
	"pg_cheat_funcs": {Package: "pg-cheat-funcs", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_checksums": {Package: "pg-checksums", NeedsPreload: false, Repo: "PGDG"},
	"pg_cjk_parser": {Package: "pg-cjk-parser", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_clickhouse": {Package: "clickhouse", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_column_tetris": {Package: "pg-column-tetris", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_cooldown": {Package: "pg-cooldown", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_crash": {Package: "pg-crash", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_cron": {Package: "cron", NeedsPreload: true, Repo: "PGDG"},
	"pg_csv": {Package: "pg-csv", NeedsPreload: false, Repo: "MIXED"},
	"pg_curl": {Package: "pg-curl", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_datasentinel": {Package: "pg-datasentinel", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_describe": {Package: "pg-describe", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_dirtyread": {Package: "dirtyread", NeedsPreload: false, Repo: "MIXED"},
	"pg_disorder": {Package: "pg-disorder", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_dispatch": {Package: "pg-dispatch", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_drop_events": {Package: "pg-drop-events", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_duckdb": {Package: "pg-duckdb", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_ducklake": {Package: "pg-ducklake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_durable": {Package: "pg-durable", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_duration": {Package: "pg-duration", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_eviltransform": {Package: "eviltransform", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_extension_base": {Package: "pg-lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_extension_updater": {Package: "pg-lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_extra_time": {Package: "pg-extra-time", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_fkpart": {Package: "pg-fkpart", NeedsPreload: false, Repo: "MIXED"},
	"pg_fsql": {Package: "pg-fsql", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_fts": {Package: "pg-fts", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_geohash": {Package: "pg-geohash", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_graphql": {Package: "pg-graphql", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_hashids": {Package: "pg-hashids", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_hint_plan": {Package: "pg-hint-plan", NeedsPreload: true, Repo: "PGDG"},
	"pg_html5_email_address": {Package: "pg-html5-email-address", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_idkit": {Package: "pg-idkit", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_incremental": {Package: "pg-incremental", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_isok": {Package: "pg-isok", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_ivm": {Package: "pg-ivm", NeedsPreload: true, Repo: "MIXED"},
	"pg_jieba": {Package: "pg-jieba", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_jsonschema": {Package: "pg-jsonschema", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_kazsearch": {Package: "pg-kazsearch", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_lake": {Package: "pg-lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_lake_copy": {Package: "pg-lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_lake_engine": {Package: "pg-lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_lake_iceberg": {Package: "pg-lake", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_lake_table": {Package: "pg-lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_later": {Package: "pg-later", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_liquid": {Package: "pg-liquid", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_local_cache": {Package: "pg-local-cache", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_map": {Package: "pg-lake", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_math": {Package: "pg-math", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_mentat": {Package: "pg-mentat", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_mockable": {Package: "pg-mockable", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_mooncake": {Package: "pg-mooncake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_net": {Package: "pg-net", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_orca": {Package: "pg-orca", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_orphaned": {Package: "pg-orphaned", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_parquet": {Package: "pg-parquet", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_partman": {Package: "partman", NeedsPreload: false, Repo: "PGDG"},
	"pg_pathcheck": {Package: "pg-pathcheck", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_permissions": {Package: "pg-permissions", NeedsPreload: false, Repo: "PGDG"},
	"pg_pinyin": {Package: "pinyin", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_polyline": {Package: "pg-polyline", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_proctab": {Package: "pgnodemx", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_profile": {Package: "pg-profile", NeedsPreload: false, Repo: "MIXED"},
	"pg_protobuf": {Package: "pg-protobuf", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_qualstats": {Package: "pg-qualstats", NeedsPreload: true, Repo: "PGDG"},
	"pg_query_rewrite": {Package: "pg-query-rewrite", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_rational": {Package: "rational", NeedsPreload: false, Repo: "MIXED"},
	"pg_readme": {Package: "pg-readme", NeedsPreload: false, Repo: "MIXED"},
	"pg_readme_test_extension": {Package: "pg-readme", NeedsPreload: false, Repo: "MIXED"},
	"pg_readonly": {Package: "pg-readonly", NeedsPreload: true, Repo: "MIXED"},
	"pg_regresql": {Package: "pg-regresql", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_relation_sql": {Package: "pg-relation-sql", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_render": {Package: "pg-render", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_repack": {Package: "repack", NeedsPreload: false, Repo: "PGDG"},
	"pg_retry": {Package: "retry", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_rewrite": {Package: "pg-rewrite", NeedsPreload: true, Repo: "MIXED"},
	"pg_rrf": {Package: "pg-rrf", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_rrule": {Package: "pg-rrule", NeedsPreload: false, Repo: "MIXED"},
	"pg_savior": {Package: "pg-savior", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_search": {Package: "pg-search", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_show_plans": {Package: "show-plans", NeedsPreload: true, Repo: "PGDG"},
	"pg_similarity": {Package: "similarity", NeedsPreload: false, Repo: "MIXED"},
	"pg_slug_gen": {Package: "pg-slug-gen", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_smtp_client": {Package: "pg-smtp-client", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_sorted_heap": {Package: "pg-sorted-heap", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_sphere": {Package: "pgsphere", NeedsPreload: false, Repo: "MIXED"},
	"pg_sqlog": {Package: "pg-sqlog", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_squeeze": {Package: "squeeze", NeedsPreload: true, Repo: "PGDG"},
	"pg_stat_backtrace": {Package: "pg-stat-backtrace", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_stat_ch": {Package: "pg-stat-ch", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_stat_kcache": {Package: "pg-stat-kcache", NeedsPreload: true, Repo: "PGDG"},
	"pg_stat_log": {Package: "stat-log", NeedsPreload: true, Repo: "PGDG"},
	"pg_stat_monitor": {Package: "pg-stat-monitor", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_stat_plans": {Package: "pg-stat-plans", NeedsPreload: true, Repo: "PGDG"},
	"pg_statviz": {Package: "statviz", NeedsPreload: false, Repo: "PGDG"},
	"pg_stl": {Package: "pg-stl", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_store_plans": {Package: "pg-store-plan", NeedsPreload: true, Repo: "MIXED"},
	"pg_strict": {Package: "pg-strict", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_strom": {Package: "pg_strom", NeedsPreload: false, Repo: "PGDG"},
	"pg_summarize": {Package: "pg-summarize", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_task": {Package: "pg-task", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_text_semver": {Package: "pg-text-semver", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_textsearch": {Package: "textsearch", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_tiktoken": {Package: "pg-tiktoken", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_tiktoken_c": {Package: "pg-tiktoken-c", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_tle": {Package: "pg-tle", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_tokenizer": {Package: "pg-tokenizer", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_tracing": {Package: "pg-tracing", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_track_optimizer": {Package: "pg-track-optimizer", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_track_settings": {Package: "pg-track-settings", NeedsPreload: false, Repo: "PGDG"},
	"pg_trickle": {Package: "pg-trickle", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_ttl_index": {Package: "ttl-index", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_turbovec": {Package: "pg-turbovec", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_upless": {Package: "pg-upless", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_uuid_v8": {Package: "pg-uuid-v8", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_uuidv7": {Package: "pg-uuidv7", NeedsPreload: false, Repo: "MIXED"},
	"pg_variables": {Package: "pg-variables", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_wait_sampling": {Package: "pg-wait-sampling", NeedsPreload: true, Repo: "MIXED"},
	"pg_when": {Package: "pg-when", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_xenophile": {Package: "pg-xenophile", NeedsPreload: false, Repo: "PIGSTY"},
	"pgagent": {Package: "pgagent", NeedsPreload: false, Repo: "PGDG"},
	"pgautofailover": {Package: "auto-failover", NeedsPreload: true, Repo: "PGDG"},
	"pgbson": {Package: "pgbson", NeedsPreload: false, Repo: "PIGSTY"},
	"pgcalendar": {Package: "pgcalendar", NeedsPreload: false, Repo: "PIGSTY"},
	"pgcontext": {Package: "pgcontext", NeedsPreload: false, Repo: "PIGSTY"},
	"pgcontext_pgvector": {Package: "pgcontext", NeedsPreload: false, Repo: "PIGSTY"},
	"pgcozy": {Package: "pgcozy", NeedsPreload: false, Repo: "PIGSTY"},
	"pgdd": {Package: "pgdd", NeedsPreload: false, Repo: "PIGSTY"},
	"pgdisablelogerror": {Package: "pgdisablelogerror", NeedsPreload: true, Repo: "PGDG"},
	"pgelog": {Package: "pgelog", NeedsPreload: false, Repo: "PIGSTY"},
	"pgfaceting": {Package: "pgfaceting", NeedsPreload: false, Repo: "MIXED"},
	"pgfincore": {Package: "pgfincore", NeedsPreload: false, Repo: "PGDG"},
	"pgfr_analyze": {Package: "pg-flight-recorder", NeedsPreload: false, Repo: "PIGSTY"},
	"pgfr_record": {Package: "pg-flight-recorder", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_consistency": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_hgm": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_output": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_output_en_au": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_output_pt_br": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_raster": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pghydro": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgjq": {Package: "pgjq", NeedsPreload: false, Repo: "PIGSTY"},
	"pgjwt": {Package: "pgjwt", NeedsPreload: false, Repo: "PIGSTY"},
	"pglinter": {Package: "pglinter", NeedsPreload: false, Repo: "PIGSTY"},
	"pglite_fusion": {Package: "pglite-fusion", NeedsPreload: true, Repo: "PIGSTY"},
	"pglock": {Package: "pglock", NeedsPreload: false, Repo: "PIGSTY"},
	"pgmb": {Package: "pgmb", NeedsPreload: false, Repo: "PIGSTY"},
	"pgmeminfo": {Package: "pgmeminfo", NeedsPreload: false, Repo: "MIXED"},
	"pgml": {Package: "pgml", NeedsPreload: true, Repo: "PIGSTY"},
	"pgmnemo": {Package: "pgmnemo", NeedsPreload: false, Repo: "PIGSTY"},
	"pgmonitor": {Package: "pgmonitor", NeedsPreload: true, Repo: "PIGSTY"},
	"pgmp": {Package: "pgmp", NeedsPreload: false, Repo: "PIGSTY"},
	"pgmq": {Package: "pgmq", NeedsPreload: false, Repo: "PIGSTY"},
	"pgnodemx": {Package: "pgnodemx", NeedsPreload: true, Repo: "PIGSTY"},
	"pgpcre": {Package: "pgpcre", NeedsPreload: false, Repo: "MIXED"},
	"pgpdf": {Package: "pgpdf", NeedsPreload: true, Repo: "PIGSTY"},
	"pgpool_adm": {Package: "pgpool2", NeedsPreload: false, Repo: "PGDG"},
	"pgpool_recovery": {Package: "pgpool2", NeedsPreload: false, Repo: "PGDG"},
	"pgpool_regclass": {Package: "pgpool2", NeedsPreload: false, Repo: "PGDG"},
	"pgproto": {Package: "pgproto", NeedsPreload: false, Repo: "PIGSTY"},
	"pgq": {Package: "pgq", NeedsPreload: false, Repo: "PGDG"},
	"pgqr": {Package: "pgqr", NeedsPreload: false, Repo: "PIGSTY"},
	"pgrdf": {Package: "pgrdf", NeedsPreload: true, Repo: "PIGSTY"},
	"pgroonga": {Package: "pgroonga", NeedsPreload: false, Repo: "PIGSTY"},
	"pgroonga_database": {Package: "pgroonga", NeedsPreload: false, Repo: "PIGSTY"},
	"pgrouting": {Package: "pgrouting", NeedsPreload: false, Repo: "PGDG"},
	"pgsentinel": {Package: "pgsentinel", NeedsPreload: true, Repo: "MIXED"},
	"pgsql_tweaks": {Package: "pgsql-tweaks", NeedsPreload: false, Repo: "PIGSTY"},
	"pgsqlmock": {Package: "pgsqlmock", NeedsPreload: false, Repo: "PIGSTY"},
	"pgtap": {Package: "pgtap", NeedsPreload: false, Repo: "PGDG"},
	"pguecc": {Package: "pg-ecdsa", NeedsPreload: false, Repo: "PIGSTY"},
	"pgwasm": {Package: "pgwasm", NeedsPreload: false, Repo: "PIGSTY"},
	"pgx_ulid": {Package: "pgx-ulid", NeedsPreload: true, Repo: "PIGSTY"},
	"plan_filter": {Package: "pg-plan-filter", NeedsPreload: true, Repo: "PIGSTY"},
	"pldbgapi": {Package: "pldebugger", NeedsPreload: true, Repo: "PGDG"},
	"pljava": {Package: "pljava", NeedsPreload: false, Repo: "PGDG"},
	"pljs": {Package: "pljs", NeedsPreload: false, Repo: "MIXED"},
	"pllua": {Package: "pllua", NeedsPreload: false, Repo: "MIXED"},
	"plluau": {Package: "pllua", NeedsPreload: false, Repo: "MIXED"},
	"plpgsql_check": {Package: "plpgsql-check", NeedsPreload: false, Repo: "PIGSTY"},
	"plprofiler": {Package: "plprofiler", NeedsPreload: true, Repo: "PGDG"},
	"plproxy": {Package: "plproxy", NeedsPreload: false, Repo: "MIXED"},
	"plprql": {Package: "plprql", NeedsPreload: false, Repo: "PIGSTY"},
	"plr": {Package: "plr", NeedsPreload: false, Repo: "PGDG"},
	"plruby": {Package: "plruby", NeedsPreload: false, Repo: "PIGSTY"},
	"plsh": {Package: "plsh", NeedsPreload: false, Repo: "PGDG"},
	"plv8": {Package: "plv8", NeedsPreload: false, Repo: "PIGSTY"},
	"plx": {Package: "plx", NeedsPreload: false, Repo: "PIGSTY"},
	"plxslt": {Package: "plxslt", NeedsPreload: false, Repo: "PGDG"},
	"pointcloud": {Package: "pointcloud", NeedsPreload: false, Repo: "PGDG"},
	"pointcloud_postgis": {Package: "pointcloud", NeedsPreload: false, Repo: "PGDG"},
	"postbis": {Package: "postbis", NeedsPreload: false, Repo: "PIGSTY"},
	"postgis": {Package: "postgis-3", NeedsPreload: false, Repo: "PGDG"},
	"postgis_raster": {Package: "postgis-3", NeedsPreload: false, Repo: "PGDG"},
	"postgis_sfcgal": {Package: "postgis-3", NeedsPreload: false, Repo: "PGDG"},
	"postgis_tiger_geocoder": {Package: "postgis-3", NeedsPreload: false, Repo: "PGDG"},
	"postgis_topology": {Package: "postgis-3", NeedsPreload: false, Repo: "PGDG"},
	"pre_prepare": {Package: "preprepare", NeedsPreload: false, Repo: "MIXED"},
	"prefix": {Package: "prefix", NeedsPreload: false, Repo: "PGDG"},
	"prioritize": {Package: "prioritize", NeedsPreload: false, Repo: "PGDG"},
	"provsql": {Package: "provsql", NeedsPreload: true, Repo: "PIGSTY"},
	"psql_bm25s": {Package: "psql-bm25s", NeedsPreload: false, Repo: "PIGSTY"},
	"q3c": {Package: "q3c", NeedsPreload: false, Repo: "PGDG"},
	"qdgc": {Package: "qdgc", NeedsPreload: false, Repo: "PIGSTY"},
	"qdgc_postgis": {Package: "qdgc", NeedsPreload: false, Repo: "PIGSTY"},
	"qos": {Package: "qos", NeedsPreload: true, Repo: "PIGSTY"},
	"quantile": {Package: "quantile", NeedsPreload: false, Repo: "PIGSTY"},
	"random": {Package: "random", NeedsPreload: false, Repo: "PIGSTY"},
	"rdkit": {Package: "rdkit", NeedsPreload: false, Repo: "MIXED"},
	"re2": {Package: "re2", NeedsPreload: false, Repo: "PIGSTY"},
	"roaringbitmap": {Package: "roaringbitmap", NeedsPreload: false, Repo: "PGDG"},
	"rum": {Package: "rum", NeedsPreload: false, Repo: "MIXED"},
	"safeupdate": {Package: "pg-safeupdate", NeedsPreload: true, Repo: "PGDG"},
	"schedoc": {Package: "pg-schedoc", NeedsPreload: false, Repo: "PIGSTY"},
	"semver": {Package: "semver", NeedsPreload: false, Repo: "PGDG"},
	"sequential_uuids": {Package: "sequential-uuids", NeedsPreload: false, Repo: "MIXED"},
	"shacrypt": {Package: "shacrypt", NeedsPreload: false, Repo: "PIGSTY"},
	"smlar": {Package: "smlar", NeedsPreload: false, Repo: "PIGSTY"},
	"snowflake": {Package: "snowflake", NeedsPreload: false, Repo: "PIGSTY"},
	"sparql": {Package: "pgsparql", NeedsPreload: false, Repo: "PIGSTY"},
	"storage_engine": {Package: "storage-engine", NeedsPreload: true, Repo: "PIGSTY"},
	"system_stats": {Package: "system-stats", NeedsPreload: false, Repo: "MIXED"},
	"table_log": {Package: "table_log", NeedsPreload: false, Repo: "MIXED"},
	"table_version": {Package: "table-version", NeedsPreload: false, Repo: "MIXED"},
	"tdigest": {Package: "tdigest", NeedsPreload: false, Repo: "PGDG"},
	"temporal_tables": {Package: "temporal-tables", NeedsPreload: false, Repo: "PIGSTY"},
	"timescaledb": {Package: "timescaledb", NeedsPreload: true, Repo: "PIGSTY"},
	"timescaledb_toolkit": {Package: "timescaledb-toolkit", NeedsPreload: false, Repo: "PIGSTY"},
	"timeseries": {Package: "pg-timeseries", NeedsPreload: false, Repo: "PIGSTY"},
	"timestamp9": {Package: "timestamp9", NeedsPreload: false, Repo: "MIXED"},
	"toastinfo": {Package: "toastinfo", NeedsPreload: false, Repo: "MIXED"},
	"topn": {Package: "topn", NeedsPreload: false, Repo: "PGDG"},
	"typeid": {Package: "typeid", NeedsPreload: false, Repo: "PIGSTY"},
	"tzf": {Package: "tzf", NeedsPreload: false, Repo: "PIGSTY"},
	"uint": {Package: "pguint", NeedsPreload: false, Repo: "MIXED"},
	"uint128": {Package: "pg-uint128", NeedsPreload: false, Repo: "PIGSTY"},
	"ulak": {Package: "ulak", NeedsPreload: true, Repo: "PIGSTY"},
	"unit": {Package: "unit", NeedsPreload: false, Repo: "PGDG"},
	"uri": {Package: "pg-uri", NeedsPreload: false, Repo: "PIGSTY"},
	"url_encode": {Package: "url-encode", NeedsPreload: false, Repo: "PIGSTY"},
	"vasco": {Package: "vasco", NeedsPreload: false, Repo: "PIGSTY"},
	"vchord": {Package: "vchord", NeedsPreload: true, Repo: "PIGSTY"},
	"vchord_bm25": {Package: "vchord-bm25", NeedsPreload: true, Repo: "PIGSTY"},
	"vector": {Package: "pgvector", NeedsPreload: false, Repo: "PGDG"},
	"vectorize": {Package: "pg-vectorize", NeedsPreload: true, Repo: "PIGSTY"},
	"vectorscale": {Package: "pgvectorscale", NeedsPreload: false, Repo: "PIGSTY"},
	"weighted_statistics": {Package: "weighted-statistics", NeedsPreload: false, Repo: "PIGSTY"},
	"xicor": {Package: "pgxicor", NeedsPreload: false, Repo: "PIGSTY"},
	"xxhash": {Package: "pg-xxhash", NeedsPreload: false, Repo: "PIGSTY"},
	"zhparser": {Package: "zhparser", NeedsPreload: false, Repo: "PIGSTY"},
	"zstd": {Package: "zstd", NeedsPreload: false, Repo: "PIGSTY"},
}

// BuiltinExt contains metadata for a contrib extension in the base image.
type BuiltinExt struct {
	NeedsPreload bool // must be in shared_preload_libraries
}

// BuiltinExts contains contrib extensions already in the postgres:18 base image.
// These require no apt install — they ship in /usr/share/postgresql/18/extension/.
var BuiltinExts = map[string]BuiltinExt{
	"amcheck":            {},
	"autoinc":            {},
	"bloom":              {},
	"btree_gin":          {},
	"btree_gist":         {},
	"citext":             {},
	"cube":               {},
	"dblink":             {},
	"dict_int":           {},
	"dict_xsyn":          {},
	"earthdistance":      {},
	"file_fdw":           {},
	"fuzzystrmatch":      {},
	"hstore":             {},
	"insert_username":    {},
	"intagg":             {},
	"intarray":           {},
	"isn":                {},
	"lo":                 {},
	"ltree":              {},
	"moddatetime":        {},
	"pageinspect":        {},
	"pg_buffercache":     {},
	"pg_freespacemap":    {},
	"pg_logicalinspect":  {},
	"pg_prewarm":         {NeedsPreload: true},
	"pg_stat_statements": {NeedsPreload: true},
	"pg_surgery":         {},
	"pg_trgm":            {},
	"pg_visibility":      {},
	"pg_walinspect":      {},
	"pgcrypto":           {},
	"pgrowlocks":         {},
	"pgstattuple":        {},
	"postgres_fdw":       {},
	"refint":             {},
	"seg":                {},
	"sslinfo":            {},
	"tablefunc":          {},
	"tcn":                {},
	"tsm_system_rows":    {},
	"tsm_system_time":    {},
	"unaccent":           {},
	"uuid-ossp":          {},
	"xml2":               {},
}

// LookupExtension returns (Package, NeedsPreload, Builtin, found) for an extension name.
// Checks BuiltinExts first (always available), then PigstyExtMap.
func LookupExtension(name string) (pkg string, needsPreload bool, builtin bool, found bool) {
	if ext, ok := BuiltinExts[name]; ok {
		return "", ext.NeedsPreload, true, true
	}
	if ext, ok := PigstyExtMap[name]; ok {
		return ext.Package, ext.NeedsPreload, false, true
	}
	return "", false, false, false
}
