package podman

// PigstyExt contains metadata for a non-builtin PostgreSQL extension
// from the Pigsty DEB repository (https://pigsty.cc/ext/list/).
// Source: pigsty.cc/ext/list/ (2026-08-31)
type PigstyExt struct {
	Package      string // apt package suffix (postgresql-18-<Package>)
	NeedsPreload bool   // must be in shared_preload_libraries
	Repo         string // source repo: PIGSTY, PGDG, MIXED
}

// PigstyExtMap contains 395 non-builtin extensions from the Pigsty catalog.
// Keyed by SQL extension name (as used in CREATE EXTENSION).
// The Package field is the apt package suffix: postgresql-18-<Package>.
var PigstyExtMap = map[string]PigstyExt{
	"acl": {Package: "pg_acl", NeedsPreload: false, Repo: "PIGSTY"},
	"address_standardizer": {Package: "postgis", NeedsPreload: false, Repo: "PGDG"},
	"address_standardizer_data_us": {Package: "postgis", NeedsPreload: false, Repo: "PGDG"},
	"age": {Package: "age", NeedsPreload: true, Repo: "PIGSTY"},
	"aggs_for_arrays": {Package: "aggs_for_arrays", NeedsPreload: false, Repo: "PIGSTY"},
	"aggs_for_vecs": {Package: "aggs_for_vecs", NeedsPreload: false, Repo: "PIGSTY"},
	"argm": {Package: "argm", NeedsPreload: false, Repo: "PIGSTY"},
	"arraymath": {Package: "pg_arraymath", NeedsPreload: false, Repo: "PIGSTY"},
	"asn1oid": {Package: "asn1oid", NeedsPreload: false, Repo: "MIXED"},
	"base36": {Package: "pg_base36", NeedsPreload: false, Repo: "PIGSTY"},
	"base62": {Package: "pg_base62", NeedsPreload: false, Repo: "PIGSTY"},
	"bgw_replstatus": {Package: "bgw_replstatus", NeedsPreload: true, Repo: "PGDG"},
	"biscuit": {Package: "pg_biscuit", NeedsPreload: false, Repo: "PIGSTY"},
	"byteamagic": {Package: "pg_byteamagic", NeedsPreload: false, Repo: "PIGSTY"},
	"bzip": {Package: "pg_bzip", NeedsPreload: false, Repo: "PIGSTY"},
	"cat_tools": {Package: "cat_tools", NeedsPreload: false, Repo: "PIGSTY"},
	"chkpass": {Package: "chkpass", NeedsPreload: false, Repo: "PIGSTY"},
	"citus": {Package: "citus", NeedsPreload: true, Repo: "PIGSTY"},
	"citus_columnar": {Package: "citus", NeedsPreload: false, Repo: "PIGSTY"},
	"collection": {Package: "pgcollection", NeedsPreload: false, Repo: "PIGSTY"},
	"columnar": {Package: "hydra", NeedsPreload: false, Repo: "PIGSTY"},
	"convert": {Package: "pg_convert", NeedsPreload: false, Repo: "PIGSTY"},
	"count_distinct": {Package: "count_distinct", NeedsPreload: false, Repo: "MIXED"},
	"country": {Package: "pg_country", NeedsPreload: false, Repo: "PIGSTY"},
	"cron_utils": {Package: "cron_utils", NeedsPreload: false, Repo: "PIGSTY"},
	"cryptint": {Package: "cryptint", NeedsPreload: false, Repo: "PIGSTY"},
	"currency": {Package: "pg_currency", NeedsPreload: false, Repo: "PIGSTY"},
	"data_historization": {Package: "data_historization", NeedsPreload: false, Repo: "PIGSTY"},
	"datasketches": {Package: "datasketches", NeedsPreload: false, Repo: "PIGSTY"},
	"dbt2": {Package: "dbt2", NeedsPreload: false, Repo: "MIXED"},
	"ddl_historization": {Package: "ddl_historization", NeedsPreload: false, Repo: "PIGSTY"},
	"ddlx": {Package: "pg_ddlx", NeedsPreload: false, Repo: "MIXED"},
	"ddsketch": {Package: "ddsketch", NeedsPreload: false, Repo: "PIGSTY"},
	"debversion": {Package: "debversion", NeedsPreload: false, Repo: "PGDG"},
	"duckdb_fdw": {Package: "duckdb_fdw", NeedsPreload: false, Repo: "PIGSTY"},
	"emailaddr": {Package: "pg_emailaddr", NeedsPreload: false, Repo: "PIGSTY"},
	"emaj": {Package: "emaj", NeedsPreload: false, Repo: "PIGSTY"},
	"envvar": {Package: "pg_envvar", NeedsPreload: false, Repo: "PIGSTY"},
	"external_file": {Package: "external_file", NeedsPreload: false, Repo: "PIGSTY"},
	"extra_window_functions": {Package: "extra_window_functions", NeedsPreload: false, Repo: "PGDG"},
	"faker": {Package: "faker", NeedsPreload: false, Repo: "MIXED"},
	"fbsql": {Package: "fbsql", NeedsPreload: false, Repo: "PIGSTY"},
	"financial": {Package: "pg_financial", NeedsPreload: false, Repo: "PIGSTY"},
	"fio": {Package: "pg_fio", NeedsPreload: false, Repo: "PIGSTY"},
	"first_last_agg": {Package: "first_last_agg", NeedsPreload: false, Repo: "MIXED"},
	"floatfile": {Package: "floatfile", NeedsPreload: false, Repo: "PIGSTY"},
	"floatvec": {Package: "floatvec", NeedsPreload: false, Repo: "PIGSTY"},
	"fsm_core": {Package: "fsm_core", NeedsPreload: false, Repo: "PIGSTY"},
	"geoip": {Package: "geoip", NeedsPreload: false, Repo: "MIXED"},
	"graph": {Package: "pggraph", NeedsPreload: false, Repo: "PIGSTY"},
	"gzip": {Package: "pg_gzip", NeedsPreload: false, Repo: "MIXED"},
	"h3": {Package: "pg_h3", NeedsPreload: false, Repo: "PGDG"},
	"h3_postgis": {Package: "pg_h3", NeedsPreload: false, Repo: "PGDG"},
	"hashlib": {Package: "pg_hashlib", NeedsPreload: false, Repo: "PIGSTY"},
	"hashtypes": {Package: "hashtypes", NeedsPreload: false, Repo: "PIGSTY"},
	"hll": {Package: "hll", NeedsPreload: false, Repo: "PGDG"},
	"hstore_pllua": {Package: "pllua", NeedsPreload: false, Repo: "MIXED"},
	"hstore_plluau": {Package: "pllua", NeedsPreload: false, Repo: "MIXED"},
	"hstore_plruby": {Package: "plruby", NeedsPreload: false, Repo: "PIGSTY"},
	"http": {Package: "pg_http", NeedsPreload: false, Repo: "PGDG"},
	"hunspell_cs_cz": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_de_de": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_en_us": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_fr": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_ne_np": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_nl_nl": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_nn_no": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_pt_pt": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_ru_ru": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hunspell_ru_ru_aot": {Package: "hunspell", NeedsPreload: false, Repo: "PIGSTY"},
	"hypopg": {Package: "hypopg", NeedsPreload: false, Repo: "PGDG"},
	"icu_ext": {Package: "icu_ext", NeedsPreload: false, Repo: "PGDG"},
	"imgsmlr": {Package: "imgsmlr", NeedsPreload: false, Repo: "PIGSTY"},
	"index_advisor": {Package: "index_advisor", NeedsPreload: false, Repo: "PIGSTY"},
	"ip4r": {Package: "ip4r", NeedsPreload: false, Repo: "PGDG"},
	"jsonb_plruby": {Package: "plruby", NeedsPreload: false, Repo: "PIGSTY"},
	"jsonschema": {Package: "jsonschema", NeedsPreload: false, Repo: "PIGSTY"},
	"jsquery": {Package: "jsquery", NeedsPreload: false, Repo: "PGDG"},
	"l10n_table_dependent_extension": {Package: "pg_xenophile", NeedsPreload: false, Repo: "PIGSTY"},
	"lower_quantile": {Package: "lower_quantile", NeedsPreload: false, Repo: "PIGSTY"},
	"ltree_plruby": {Package: "plruby", NeedsPreload: false, Repo: "PIGSTY"},
	"md5hash": {Package: "md5hash", NeedsPreload: false, Repo: "PIGSTY"},
	"meta": {Package: "pg_meta", NeedsPreload: false, Repo: "PIGSTY"},
	"mobilitydb": {Package: "mobilitydb", NeedsPreload: true, Repo: "MIXED"},
	"mobilitydb_datagen": {Package: "mobilitydb", NeedsPreload: false, Repo: "MIXED"},
	"numeral": {Package: "numeral", NeedsPreload: false, Repo: "MIXED"},
	"ogr_fdw": {Package: "ogr_fdw", NeedsPreload: false, Repo: "PGDG"},
	"omni": {Package: "omnigres", NeedsPreload: true, Repo: "PIGSTY"},
	"omni_auth": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_aws": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_cloudevents": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_containers": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_credentials": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_csv": {Package: "omni_csv", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_datasets": {Package: "omni_datasets", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_email": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_http": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_httpc": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_httpd": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_id": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_json": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_kube": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_ledger": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_manifest": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_mimetypes": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_os": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_polyfill": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_python": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_regex": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_rest": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_schema": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_seq": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_service": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_session": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_shmem": {Package: "omni_shmem", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_sql": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_sqlite": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_test": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_txn": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_types": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_var": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_vfs": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_vfs_types_v1": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_web": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_worker": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_xml": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omni_yaml": {Package: "omnigres", NeedsPreload: false, Repo: "PIGSTY"},
	"omnisketch": {Package: "omnisketch", NeedsPreload: false, Repo: "PIGSTY"},
	"onesparse": {Package: "one_sparse", NeedsPreload: false, Repo: "PIGSTY"},
	"online_advisor": {Package: "online_advisor", NeedsPreload: true, Repo: "PIGSTY"},
	"orioledb": {Package: "orioledb", NeedsPreload: true, Repo: "PIGSTY"},
	"parray_gin": {Package: "parray_gin", NeedsPreload: false, Repo: "PIGSTY"},
	"periods": {Package: "periods", NeedsPreload: false, Repo: "PIGSTY"},
	"permuteseq": {Package: "permuteseq", NeedsPreload: false, Repo: "PIGSTY"},
	"pg4ml": {Package: "pg4ml", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_accumulator": {Package: "pg_accumulator", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_ai_query": {Package: "pg_ai_query", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_background": {Package: "pg_background", NeedsPreload: false, Repo: "PGDG"},
	"pg_base58": {Package: "pg_base58", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_bestmatch": {Package: "pg_bestmatch", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_bigm": {Package: "pg_bigm", NeedsPreload: true, Repo: "MIXED"},
	"pg_bikram_sambat": {Package: "pg_bikram_sambat", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_cardano": {Package: "pg_cardano", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_catcheck": {Package: "pg_catcheck", NeedsPreload: false, Repo: "PGDG"},
	"pg_cheat_funcs": {Package: "pg_cheat_funcs", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_checksums": {Package: "pg_checksums", NeedsPreload: false, Repo: "PGDG"},
	"pg_cjk_parser": {Package: "pg_cjk_parser", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_clickhouse": {Package: "pg_clickhouse", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_column_tetris": {Package: "pg_column_tetris", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_cooldown": {Package: "pg_cooldown", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_crash": {Package: "pg_crash", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_cron": {Package: "cron", NeedsPreload: true, Repo: "PGDG"},
	"pg_csv": {Package: "pg_csv", NeedsPreload: false, Repo: "MIXED"},
	"pg_curl": {Package: "pg_curl", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_datasentinel": {Package: "pg_datasentinel", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_describe": {Package: "pg_describe", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_dirtyread": {Package: "pg_dirtyread", NeedsPreload: false, Repo: "MIXED"},
	"pg_disorder": {Package: "pg_disorder", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_dispatch": {Package: "pg_dispatch", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_drop_events": {Package: "pg_drop_events", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_duckdb": {Package: "pg_duckdb", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_ducklake": {Package: "pg_ducklake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_durable": {Package: "pg_durable", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_duration": {Package: "pg_duration", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_eviltransform": {Package: "pg_eviltransform", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_extension_base": {Package: "pg_lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_extension_updater": {Package: "pg_lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_extra_time": {Package: "pg_extra_time", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_fkpart": {Package: "pg_fkpart", NeedsPreload: false, Repo: "MIXED"},
	"pg_fsql": {Package: "pg_fsql", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_fts": {Package: "pg_fts", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_geohash": {Package: "pg_geohash", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_graphql": {Package: "pg_graphql", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_hashids": {Package: "pg_hashids", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_hint_plan": {Package: "pg_hint_plan", NeedsPreload: true, Repo: "PGDG"},
	"pg_html5_email_address": {Package: "pg_html5_email_address", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_idkit": {Package: "pg_idkit", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_incremental": {Package: "pg_incremental", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_isok": {Package: "pg_isok", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_ivm": {Package: "pg_ivm", NeedsPreload: true, Repo: "MIXED"},
	"pg_jieba": {Package: "pg_jieba", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_jsonschema": {Package: "pg_jsonschema", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_kazsearch": {Package: "pg_kazsearch", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_lake": {Package: "pg_lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_lake_copy": {Package: "pg_lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_lake_engine": {Package: "pg_lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_lake_iceberg": {Package: "pg_lake", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_lake_table": {Package: "pg_lake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_later": {Package: "pg_later", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_liquid": {Package: "pg_liquid", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_local_cache": {Package: "pg_local_cache", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_map": {Package: "pg_lake", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_math": {Package: "pg_math", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_mentat": {Package: "pg_mentat", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_mockable": {Package: "pg_mockable", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_mooncake": {Package: "pg_mooncake", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_net": {Package: "pg_net", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_orca": {Package: "pg_orca", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_orphaned": {Package: "pg_orphaned", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_parquet": {Package: "pg_parquet", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_partman": {Package: "pg_partman", NeedsPreload: false, Repo: "PGDG"},
	"pg_pathcheck": {Package: "pg_pathcheck", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_permissions": {Package: "pg_permissions", NeedsPreload: false, Repo: "PGDG"},
	"pg_pinyin": {Package: "pg_pinyin", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_polyline": {Package: "pg_polyline", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_proctab": {Package: "pgnodemx", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_profile": {Package: "pg_profile", NeedsPreload: false, Repo: "MIXED"},
	"pg_protobuf": {Package: "pg_protobuf", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_qualstats": {Package: "pg_qualstats", NeedsPreload: true, Repo: "PGDG"},
	"pg_query_rewrite": {Package: "pg_query_rewrite", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_rational": {Package: "pg_rational", NeedsPreload: false, Repo: "MIXED"},
	"pg_readme": {Package: "pg_readme", NeedsPreload: false, Repo: "MIXED"},
	"pg_readme_test_extension": {Package: "pg_readme", NeedsPreload: false, Repo: "MIXED"},
	"pg_readonly": {Package: "pg_readonly", NeedsPreload: true, Repo: "MIXED"},
	"pg_regresql": {Package: "pg_regresql", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_relation_sql": {Package: "pg_relation_sql", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_render": {Package: "pg_render", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_repack": {Package: "pg_repack", NeedsPreload: false, Repo: "PGDG"},
	"pg_retry": {Package: "pg_retry", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_rewrite": {Package: "pg_rewrite", NeedsPreload: true, Repo: "MIXED"},
	"pg_rrf": {Package: "pg_rrf", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_rrule": {Package: "pg_rrule", NeedsPreload: false, Repo: "MIXED"},
	"pg_savior": {Package: "pg_savior", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_search": {Package: "pg_search", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_show_plans": {Package: "pg_show_plans", NeedsPreload: true, Repo: "PGDG"},
	"pg_similarity": {Package: "pg_similarity", NeedsPreload: false, Repo: "MIXED"},
	"pg_slug_gen": {Package: "pg_slug_gen", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_smtp_client": {Package: "pg_smtp_client", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_sorted_heap": {Package: "pg_sorted_heap", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_sphere": {Package: "pgsphere", NeedsPreload: false, Repo: "MIXED"},
	"pg_sqlog": {Package: "pg_sqlog", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_squeeze": {Package: "pg_squeeze", NeedsPreload: true, Repo: "PGDG"},
	"pg_stat_backtrace": {Package: "pg_stat_backtrace", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_stat_ch": {Package: "pg_stat_ch", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_stat_kcache": {Package: "pg_stat_kcache", NeedsPreload: true, Repo: "PGDG"},
	"pg_stat_log": {Package: "pg_stat_log", NeedsPreload: true, Repo: "PGDG"},
	"pg_stat_monitor": {Package: "pg_stat_monitor", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_stat_plans": {Package: "pg_stat_plans", NeedsPreload: true, Repo: "PGDG"},
	"pg_statviz": {Package: "pg_statviz", NeedsPreload: false, Repo: "PGDG"},
	"pg_stl": {Package: "pg_stl", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_store_plans": {Package: "pg_store_plans", NeedsPreload: true, Repo: "MIXED"},
	"pg_strict": {Package: "pg_strict", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_strom": {Package: "pg_strom", NeedsPreload: false, Repo: "PGDG"},
	"pg_summarize": {Package: "pg_summarize", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_task": {Package: "pg_task", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_text_semver": {Package: "pg_text_semver", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_textsearch": {Package: "pg_textsearch", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_tiktoken": {Package: "pg_tiktoken", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_tiktoken_c": {Package: "pg_tiktoken_c", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_tle": {Package: "pg_tle", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_tokenizer": {Package: "pg_tokenizer", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_tracing": {Package: "pg_tracing", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_track_optimizer": {Package: "pg_track_optimizer", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_track_settings": {Package: "pg_track_settings", NeedsPreload: false, Repo: "PGDG"},
	"pg_trickle": {Package: "pg_trickle", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_ttl_index": {Package: "pg_ttl_index", NeedsPreload: true, Repo: "PIGSTY"},
	"pg_turbovec": {Package: "pg_turbovec", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_upless": {Package: "pg_upless", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_uuid_v8": {Package: "pg_uuid_v8", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_uuidv7": {Package: "pg_uuidv7", NeedsPreload: false, Repo: "MIXED"},
	"pg_variables": {Package: "pg_variables", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_wait_sampling": {Package: "pg_wait_sampling", NeedsPreload: true, Repo: "MIXED"},
	"pg_when": {Package: "pg_when", NeedsPreload: false, Repo: "PIGSTY"},
	"pg_xenophile": {Package: "pg_xenophile", NeedsPreload: false, Repo: "PIGSTY"},
	"pgagent": {Package: "pgagent", NeedsPreload: false, Repo: "PGDG"},
	"pgautofailover": {Package: "pgautofailover", NeedsPreload: true, Repo: "PGDG"},
	"pgbson": {Package: "pgbson", NeedsPreload: false, Repo: "PIGSTY"},
	"pgcalendar": {Package: "pgcalendar", NeedsPreload: false, Repo: "PIGSTY"},
	"pgcontext": {Package: "pgcontext", NeedsPreload: false, Repo: "PIGSTY"},
	"pgcontext_pgvector": {Package: "pgcontext", NeedsPreload: false, Repo: "PIGSTY"},
	"pgcozy": {Package: "pgcozy", NeedsPreload: false, Repo: "PIGSTY"},
	"pgdd": {Package: "pgdd", NeedsPreload: false, Repo: "PIGSTY"},
	"pgdisablelogerror": {Package: "pgdisablelogerror", NeedsPreload: true, Repo: "PGDG"},
	"pgelog": {Package: "pgelog", NeedsPreload: false, Repo: "PIGSTY"},
	"pgfaceting": {Package: "pgfaceting", NeedsPreload: false, Repo: "MIXED"},
	"pgfincore": {Package: "pgfincore", NeedsPreload: false, Repo: "PGDG"},
	"pgfr_analyze": {Package: "pg_flight_recorder", NeedsPreload: false, Repo: "PIGSTY"},
	"pgfr_record": {Package: "pg_flight_recorder", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_consistency": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_hgm": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_output": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_output_en_au": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_output_pt_br": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgh_raster": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pghydro": {Package: "pghydro", NeedsPreload: false, Repo: "PIGSTY"},
	"pgjq": {Package: "pgjq", NeedsPreload: false, Repo: "PIGSTY"},
	"pgjwt": {Package: "pgjwt", NeedsPreload: false, Repo: "PIGSTY"},
	"pglinter": {Package: "pglinter", NeedsPreload: false, Repo: "PIGSTY"},
	"pglite_fusion": {Package: "pglite_fusion", NeedsPreload: true, Repo: "PIGSTY"},
	"pglock": {Package: "pglock", NeedsPreload: false, Repo: "PIGSTY"},
	"pgmb": {Package: "pgmb", NeedsPreload: false, Repo: "PIGSTY"},
	"pgmeminfo": {Package: "pgmeminfo", NeedsPreload: false, Repo: "MIXED"},
	"pgml": {Package: "pgml", NeedsPreload: true, Repo: "PIGSTY"},
	"pgmnemo": {Package: "pgmnemo", NeedsPreload: false, Repo: "PIGSTY"},
	"pgmonitor": {Package: "pgmonitor", NeedsPreload: true, Repo: "PIGSTY"},
	"pgmp": {Package: "pgmp", NeedsPreload: false, Repo: "PIGSTY"},
	"pgmq": {Package: "pgmq", NeedsPreload: false, Repo: "PIGSTY"},
	"pgnodemx": {Package: "pgnodemx", NeedsPreload: true, Repo: "PIGSTY"},
	"pgpcre": {Package: "pgpcre", NeedsPreload: false, Repo: "MIXED"},
	"pgpdf": {Package: "pgpdf", NeedsPreload: true, Repo: "PIGSTY"},
	"pgpool_adm": {Package: "pgpool", NeedsPreload: false, Repo: "PGDG"},
	"pgpool_recovery": {Package: "pgpool", NeedsPreload: false, Repo: "PGDG"},
	"pgpool_regclass": {Package: "pgpool", NeedsPreload: false, Repo: "PGDG"},
	"pgproto": {Package: "pgproto", NeedsPreload: false, Repo: "PIGSTY"},
	"pgq": {Package: "pgq", NeedsPreload: false, Repo: "PGDG"},
	"pgqr": {Package: "pgqr", NeedsPreload: false, Repo: "PIGSTY"},
	"pgrdf": {Package: "pgrdf", NeedsPreload: true, Repo: "PIGSTY"},
	"pgroonga": {Package: "pgroonga", NeedsPreload: false, Repo: "PIGSTY"},
	"pgroonga_database": {Package: "pgroonga", NeedsPreload: false, Repo: "PIGSTY"},
	"pgrouting": {Package: "pgrouting", NeedsPreload: false, Repo: "PGDG"},
	"pgsentinel": {Package: "pgsentinel", NeedsPreload: true, Repo: "MIXED"},
	"pgsql_tweaks": {Package: "pgsql_tweaks", NeedsPreload: false, Repo: "PIGSTY"},
	"pgsqlmock": {Package: "pgsqlmock", NeedsPreload: false, Repo: "PIGSTY"},
	"pgtap": {Package: "pgtap", NeedsPreload: false, Repo: "PGDG"},
	"pguecc": {Package: "pg_ecdsa", NeedsPreload: false, Repo: "PIGSTY"},
	"pgwasm": {Package: "pgwasm", NeedsPreload: false, Repo: "PIGSTY"},
	"pgx_ulid": {Package: "pgx_ulid", NeedsPreload: true, Repo: "PIGSTY"},
	"plan_filter": {Package: "pg_plan_filter", NeedsPreload: true, Repo: "PIGSTY"},
	"pldbgapi": {Package: "pldebugger", NeedsPreload: true, Repo: "PGDG"},
	"pljava": {Package: "pljava", NeedsPreload: false, Repo: "PGDG"},
	"pljs": {Package: "pljs", NeedsPreload: false, Repo: "MIXED"},
	"pllua": {Package: "pllua", NeedsPreload: false, Repo: "MIXED"},
	"plluau": {Package: "pllua", NeedsPreload: false, Repo: "MIXED"},
	"plpgsql_check": {Package: "plpgsql_check", NeedsPreload: false, Repo: "PIGSTY"},
	"plprofiler": {Package: "plprofiler", NeedsPreload: true, Repo: "PGDG"},
	"plproxy": {Package: "plproxy", NeedsPreload: false, Repo: "MIXED"},
	"plprql": {Package: "plprql", NeedsPreload: false, Repo: "PIGSTY"},
	"plr": {Package: "plr", NeedsPreload: false, Repo: "PGDG"},
	"plruby": {Package: "plruby", NeedsPreload: false, Repo: "PIGSTY"},
	"plsh": {Package: "plsh", NeedsPreload: false, Repo: "PGDG"},
	"plv8": {Package: "plv8", NeedsPreload: false, Repo: "PIGSTY"},
	"plx": {Package: "plx", NeedsPreload: false, Repo: "PIGSTY"},
	"plxslt": {Package: "plxslt", NeedsPreload: false, Repo: "PGDG"},
	"pointcloud": {Package: "pointcloud", NeedsPreload: false, Repo: "PGDG"},
	"pointcloud_postgis": {Package: "pointcloud", NeedsPreload: false, Repo: "PGDG"},
	"postbis": {Package: "postbis", NeedsPreload: false, Repo: "PIGSTY"},
	"postgis": {Package: "postgis", NeedsPreload: false, Repo: "PGDG"},
	"postgis_raster": {Package: "postgis", NeedsPreload: false, Repo: "PGDG"},
	"postgis_sfcgal": {Package: "postgis", NeedsPreload: false, Repo: "PGDG"},
	"postgis_tiger_geocoder": {Package: "postgis", NeedsPreload: false, Repo: "PGDG"},
	"postgis_topology": {Package: "postgis", NeedsPreload: false, Repo: "PGDG"},
	"pre_prepare": {Package: "preprepare", NeedsPreload: false, Repo: "MIXED"},
	"prefix": {Package: "pg_prefix", NeedsPreload: false, Repo: "PGDG"},
	"prioritize": {Package: "pg_prioritize", NeedsPreload: false, Repo: "PGDG"},
	"provsql": {Package: "provsql", NeedsPreload: true, Repo: "PIGSTY"},
	"psql_bm25s": {Package: "psql_bm25s", NeedsPreload: false, Repo: "PIGSTY"},
	"q3c": {Package: "q3c", NeedsPreload: false, Repo: "PGDG"},
	"qdgc": {Package: "qdgc", NeedsPreload: false, Repo: "PIGSTY"},
	"qdgc_postgis": {Package: "qdgc", NeedsPreload: false, Repo: "PIGSTY"},
	"qos": {Package: "pg_qos", NeedsPreload: true, Repo: "PIGSTY"},
	"quantile": {Package: "quantile", NeedsPreload: false, Repo: "PIGSTY"},
	"random": {Package: "pg_random", NeedsPreload: false, Repo: "PIGSTY"},
	"rdkit": {Package: "rdkit", NeedsPreload: false, Repo: "MIXED"},
	"re2": {Package: "re2", NeedsPreload: false, Repo: "PIGSTY"},
	"roaringbitmap": {Package: "pg_roaringbitmap", NeedsPreload: false, Repo: "PGDG"},
	"rum": {Package: "rum", NeedsPreload: false, Repo: "MIXED"},
	"safeupdate": {Package: "safeupdate", NeedsPreload: true, Repo: "PGDG"},
	"schedoc": {Package: "pg_schedoc", NeedsPreload: false, Repo: "PIGSTY"},
	"semver": {Package: "pg_semver", NeedsPreload: false, Repo: "PGDG"},
	"sequential_uuids": {Package: "sequential_uuids", NeedsPreload: false, Repo: "MIXED"},
	"shacrypt": {Package: "shacrypt", NeedsPreload: false, Repo: "PIGSTY"},
	"smlar": {Package: "smlar", NeedsPreload: false, Repo: "PIGSTY"},
	"snowflake": {Package: "snowflake", NeedsPreload: false, Repo: "PIGSTY"},
	"sparql": {Package: "pgsparql", NeedsPreload: false, Repo: "PIGSTY"},
	"storage_engine": {Package: "storage_engine", NeedsPreload: true, Repo: "PIGSTY"},
	"system_stats": {Package: "system_stats", NeedsPreload: false, Repo: "MIXED"},
	"table_log": {Package: "table_log", NeedsPreload: false, Repo: "MIXED"},
	"table_version": {Package: "table_version", NeedsPreload: false, Repo: "MIXED"},
	"tdigest": {Package: "tdigest", NeedsPreload: false, Repo: "PGDG"},
	"temporal_tables": {Package: "temporal_tables", NeedsPreload: false, Repo: "PIGSTY"},
	"timescaledb": {Package: "timescaledb", NeedsPreload: true, Repo: "PIGSTY"},
	"timescaledb_toolkit": {Package: "timescaledb_toolkit", NeedsPreload: false, Repo: "PIGSTY"},
	"timeseries": {Package: "pg_timeseries", NeedsPreload: false, Repo: "PIGSTY"},
	"timestamp9": {Package: "timestamp9", NeedsPreload: false, Repo: "MIXED"},
	"toastinfo": {Package: "toastinfo", NeedsPreload: false, Repo: "MIXED"},
	"topn": {Package: "topn", NeedsPreload: false, Repo: "PGDG"},
	"typeid": {Package: "pg_typeid", NeedsPreload: false, Repo: "PIGSTY"},
	"tzf": {Package: "pg_tzf", NeedsPreload: false, Repo: "PIGSTY"},
	"uint": {Package: "pguint", NeedsPreload: false, Repo: "MIXED"},
	"uint128": {Package: "pg_uint128", NeedsPreload: false, Repo: "PIGSTY"},
	"ulak": {Package: "ulak", NeedsPreload: true, Repo: "PIGSTY"},
	"unit": {Package: "pgunit", NeedsPreload: false, Repo: "PGDG"},
	"uri": {Package: "pg_uri", NeedsPreload: false, Repo: "PIGSTY"},
	"url_encode": {Package: "url_encode", NeedsPreload: false, Repo: "PIGSTY"},
	"vasco": {Package: "vasco", NeedsPreload: false, Repo: "PIGSTY"},
	"vchord": {Package: "vchord", NeedsPreload: true, Repo: "PIGSTY"},
	"vchord_bm25": {Package: "vchord_bm25", NeedsPreload: true, Repo: "PIGSTY"},
	"vector": {Package: "pgvector", NeedsPreload: false, Repo: "PGDG"},
	"vectorize": {Package: "pg_vectorize", NeedsPreload: true, Repo: "PIGSTY"},
	"vectorscale": {Package: "pgvectorscale", NeedsPreload: false, Repo: "PIGSTY"},
	"weighted_statistics": {Package: "pg_weighted_statistics", NeedsPreload: false, Repo: "PIGSTY"},
	"xicor": {Package: "pgxicor", NeedsPreload: false, Repo: "PIGSTY"},
	"xxhash": {Package: "pg_xxhash", NeedsPreload: false, Repo: "PIGSTY"},
	"zhparser": {Package: "zhparser", NeedsPreload: false, Repo: "PIGSTY"},
	"zstd": {Package: "pg_zstd", NeedsPreload: false, Repo: "PIGSTY"},
}

// BuiltinExt contains metadata for a contrib extension in the base image.
type BuiltinExt struct {
	NeedsPreload bool // must be in shared_preload_libraries
}

// BuiltinExts contains contrib extensions already in the postgres:18 base image.
// These require no apt install — they ship in /usr/share/postgresql/18/extension/.
var BuiltinExts = map[string]BuiltinExt{
	"amcheck":            {},
	"autoinc":            {},
	"bloom":              {},
	"btree_gin":          {},
	"btree_gist":         {},
	"citext":             {},
	"cube":               {},
	"dblink":             {},
	"dict_int":           {},
	"dict_xsyn":          {},
	"earthdistance":      {},
	"file_fdw":           {},
	"fuzzystrmatch":      {},
	"hstore":             {},
	"insert_username":    {},
	"intagg":             {},
	"intarray":           {},
	"isn":                {},
	"lo":                 {},
	"ltree":              {},
	"moddatetime":        {},
	"pageinspect":        {},
	"pg_buffercache":     {},
	"pg_freespacemap":    {},
	"pg_logicalinspect":  {},
	"pg_prewarm":         {NeedsPreload: true},
	"pg_stat_statements": {NeedsPreload: true},
	"pg_surgery":         {},
	"pg_trgm":            {},
	"pg_visibility":      {},
	"pg_walinspect":      {},
	"pgcrypto":           {},
	"pgrowlocks":         {},
	"pgstattuple":        {},
	"postgres_fdw":       {},
	"refint":             {},
	"seg":                {},
	"sslinfo":            {},
	"tablefunc":          {},
	"tcn":                {},
	"tsm_system_rows":    {},
	"tsm_system_time":    {},
	"unaccent":           {},
	"uuid-ossp":          {},
	"xml2":               {},
}

// LookupExtension returns (Package, NeedsPreload, Builtin, found) for an extension name.
// Checks BuiltinExts first (always available), then PigstyExtMap.
func LookupExtension(name string) (pkg string, needsPreload bool, builtin bool, found bool) {
	if ext, ok := BuiltinExts[name]; ok {
		return "", ext.NeedsPreload, true, true
	}
	if ext, ok := PigstyExtMap[name]; ok {
		return ext.Package, ext.NeedsPreload, false, true
	}
	return "", false, false, false
}
